import type { PageContent } from "@/lib/types";

/**
 * Pre-generated page content for reliability.
 * Used when Claude API is slow/down or during demo mode.
 */
export const CACHED_PAGES: PageContent[] = [
  // ─── EASY NEWS (Level 1-3) ───
  {
    id: "cache-news-easy-1",
    title: "Global Water Reserves Hit Record High, Scientists Report",
    contentType: "news",
    author: "Sarah Chen",
    date: "February 12, 2026",
    url: "https://worldnewsdaily.com/science/water-reserves-2026",
    difficulty: 1,
    decayDuration: 60,
    sections: [
      {
        id: "s1",
        text: "A new report from the United Nations Environment Programme has revealed that global freshwater reserves have reached unprecedented levels in 2026, contradicting decades of warnings about water scarcity.",
        isTrue: false,
        category: "headline",
        decayOrder: 5,
        archiveCost: 1,
      },
      {
        id: "s2",
        text: "The study analyzed satellite data from over 190 countries and found that improved rainfall patterns in Southeast Asia and Central Africa have contributed to a 12% increase in accessible freshwater since 2020.",
        isTrue: false,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s3",
        text: "\"While localized droughts continue to affect communities worldwide, the overall trajectory shows remarkable improvement,\" said Dr. James Okafor, lead hydrologist on the study.",
        isTrue: false,
        category: "quote",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s4",
        text: "The World Health Organization estimates that approximately 2.2 billion people still lack access to safely managed drinking water services as of 2025.",
        isTrue: true,
        category: "statistic",
        decayOrder: 2,
        archiveCost: 1,
      },
      {
        id: "s5",
        text: "Climate scientists have long warned that rising global temperatures will intensify both flooding and drought cycles, making water management increasingly challenging for governments worldwide.",
        isTrue: true,
        category: "body",
        decayOrder: 4,
        archiveCost: 1,
      },
    ],
    factCheckData: {
      sourceCredibility: 35,
      dateAccuracy: true,
      emotionalLanguageScore: 25,
      crossReferenceHits: [
        "UN reports show water scarcity is worsening, not improving",
        "WHO 2.2 billion figure is accurate from 2023 reports",
      ],
      authorHistory: "No credible byline found for 'Sarah Chen' at this outlet",
    },
  },
  // ─── EASY BLOG (Level 1-3) ───
  {
    id: "cache-blog-easy-1",
    title: "Why I Stopped Using Social Media for 30 Days (And What Happened Next)",
    contentType: "blog",
    author: "Marcus Rivera",
    date: "January 28, 2026",
    url: "https://mindfultech.blog/social-media-detox-2026",
    difficulty: 2,
    decayDuration: 55,
    sections: [
      {
        id: "s1",
        text: "After years of doom-scrolling, I decided to go cold turkey on all social media platforms for an entire month. What I discovered genuinely surprised me.",
        isTrue: true,
        category: "headline",
        decayOrder: 5,
        archiveCost: 1,
      },
      {
        id: "s2",
        text: "By day three, I noticed my attention span improving. Research from Harvard Medical School confirms that the average human attention span has dropped to just 3 seconds — shorter than a goldfish.",
        isTrue: false,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s3",
        text: "I started reading physical books again. According to the Pew Research Center, about 75% of American adults read at least one book in 2024, with print remaining the most popular format.",
        isTrue: true,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s4",
        text: "Studies have shown links between excessive social media use and increased rates of anxiety and depression, particularly among young adults aged 18-29.",
        isTrue: true,
        category: "statistic",
        decayOrder: 2,
        archiveCost: 1,
      },
      {
        id: "s5",
        text: "The \"goldfish attention span\" myth has been debunked by neuroscientists, but the feeling of improved focus without constant notifications was very real for me.",
        isTrue: true,
        category: "body",
        decayOrder: 4,
        archiveCost: 1,
      },
    ],
    factCheckData: {
      sourceCredibility: 55,
      dateAccuracy: true,
      emotionalLanguageScore: 45,
      crossReferenceHits: [
        "The 'goldfish attention span' claim is a widely debunked myth",
        "Pew reading statistics are roughly accurate",
        "Social media and mental health links are well-documented",
      ],
      authorHistory: "Personal blog, no institutional affiliation",
    },
  },
  // ─── MEDIUM SOCIAL (Level 4-6) ───
  {
    id: "cache-social-med-1",
    title: "Thread: The truth about AI job displacement that nobody is talking about",
    contentType: "social",
    author: "TechInsider_Kate",
    date: "February 10, 2026",
    url: "https://threads.social/@techinsider_kate/ai-jobs-thread",
    difficulty: 4,
    decayDuration: 40,
    sections: [
      {
        id: "s1",
        text: "THREAD: Everyone is freaking out about AI taking jobs, but the data tells a more nuanced story. Let me break it down. 🧵",
        isTrue: true,
        category: "headline",
        decayOrder: 5,
        archiveCost: 1,
      },
      {
        id: "s2",
        text: "1/ The World Economic Forum's 2025 Future of Jobs Report estimates that AI will create 97 million new jobs while displacing 85 million by 2030 — a NET POSITIVE of 12 million jobs.",
        isTrue: true,
        category: "statistic",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s3",
        text: "2/ BUT here's what they don't tell you: Goldman Sachs estimates that 92% of new AI-created jobs will require a master's degree or higher, effectively locking out the majority of displaced workers.",
        isTrue: false,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s4",
        text: "3/ Countries like Denmark and Singapore have invested heavily in workforce retraining programs. Denmark's 'flexicurity' model provides up to 2 years of government-funded reskilling.",
        isTrue: true,
        category: "body",
        decayOrder: 2,
        archiveCost: 1,
      },
      {
        id: "s5",
        text: "4/ The real risk isn't AI replacing humans — it's humans with AI replacing humans without AI. The skills gap is the actual crisis, and we're not investing nearly enough in bridging it.",
        isTrue: true,
        category: "quote",
        decayOrder: 4,
        archiveCost: 1,
      },
      {
        id: "s6",
        text: "5/ According to MIT, every $1 invested in worker retraining generates $4.70 in economic returns within 5 years. The math is clear — we just need the political will.",
        isTrue: false,
        category: "statistic",
        decayOrder: 2,
        archiveCost: 1,
      },
    ],
    factCheckData: {
      sourceCredibility: 50,
      dateAccuracy: true,
      emotionalLanguageScore: 55,
      crossReferenceHits: [
        "WEF Future of Jobs report numbers are approximately correct",
        "No Goldman Sachs report states 92% master's degree requirement",
        "Denmark's flexicurity model is real but details vary",
        "MIT retraining ROI figure cannot be verified",
      ],
      authorHistory: "Popular tech commentary account, mixes real data with unverified claims",
    },
  },
  // ─── MEDIUM WIKI (Level 4-6) ───
  {
    id: "cache-wiki-med-1",
    title: "The Aral Sea Disaster",
    contentType: "wiki",
    author: "Encyclopedia Contributors",
    date: "Last edited: February 8, 2026",
    url: "https://freeencyclopedia.org/wiki/Aral_Sea_disaster",
    difficulty: 5,
    decayDuration: 40,
    sections: [
      {
        id: "s1",
        text: "The Aral Sea, once the fourth-largest lake in the world, has been steadily shrinking since the 1960s due to Soviet-era irrigation projects that diverted its two main tributary rivers.",
        isTrue: true,
        category: "headline",
        decayOrder: 5,
        archiveCost: 1,
      },
      {
        id: "s2",
        text: "Located between Kazakhstan and Uzbekistan, the Aral Sea covered approximately 68,000 square kilometers in 1960. By 2015, the eastern basin had completely dried up for the first time in modern history.",
        isTrue: true,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s3",
        text: "The ecological impact has been devastating. The exposed seabed, contaminated with pesticide residue, has created toxic dust storms that have increased respiratory illness rates in surrounding communities by an estimated 800%.",
        isTrue: false,
        category: "statistic",
        decayOrder: 2,
        archiveCost: 1,
      },
      {
        id: "s4",
        text: "Kazakhstan's Kok-Aral Dam, completed in 2005, has helped partially restore the North Aral Sea. Water levels in the northern basin rose by 12 meters between 2005 and 2015, and fish populations have begun to recover.",
        isTrue: true,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s5",
        text: "The fishing industry, which once employed over 60,000 people in the region, collapsed entirely by 1982. The port city of Moynaq, once on the shoreline, now sits over 150 kilometers from the water's edge.",
        isTrue: false,
        category: "body",
        decayOrder: 4,
        archiveCost: 1,
      },
      {
        id: "s6",
        text: "The United Nations has described the Aral Sea disaster as \"one of the planet's worst environmental catastrophes.\" Restoration efforts continue but full recovery is considered impossible.",
        isTrue: true,
        category: "attribution",
        decayOrder: 1,
        archiveCost: 1,
      },
    ],
    factCheckData: {
      sourceCredibility: 70,
      dateAccuracy: true,
      emotionalLanguageScore: 30,
      crossReferenceHits: [
        "Aral Sea size and shrinkage timeline is well-documented",
        "800% respiratory illness increase is exaggerated — real increase is significant but lower",
        "Kok-Aral Dam restoration details are accurate",
        "Moynaq distance from water is approximately 100-150km but fishing industry decline was more gradual",
      ],
      authorHistory: "Community-edited encyclopedia — generally reliable but check specific statistics",
    },
  },
  // ─── HARD NEWS (Level 7-9) ───
  {
    id: "cache-news-hard-1",
    title: "New Study Links Urban Green Spaces to 15% Reduction in Crime Rates",
    contentType: "news",
    author: "David Park",
    date: "February 5, 2026",
    url: "https://metropolitanreview.com/urban/green-spaces-crime-2026",
    difficulty: 7,
    decayDuration: 25,
    sections: [
      {
        id: "s1",
        text: "A comprehensive study published in the Journal of Urban Planning found that cities investing in green infrastructure saw measurable reductions in both violent and property crime over a five-year period.",
        isTrue: true,
        category: "headline",
        decayOrder: 5,
        archiveCost: 1,
      },
      {
        id: "s2",
        text: "Researchers analyzed crime data from 87 U.S. cities between 2019 and 2024, controlling for socioeconomic factors, policing changes, and population shifts. Cities that increased green space by at least 10% saw an average 15% drop in overall crime.",
        isTrue: true,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s3",
        text: "\"The mechanism is straightforward,\" explained Dr. Lisa Huang, the study's lead author. \"Green spaces increase foot traffic, create informal surveillance, and reduce the psychological stress that correlates with aggressive behavior.\"",
        isTrue: true,
        category: "quote",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s4",
        text: "The study found that the effect was strongest in neighborhoods with median household incomes below $35,000, where crime reductions averaged 23%. This suggests green spaces may be most impactful in underserved communities.",
        isTrue: false,
        category: "statistic",
        decayOrder: 2,
        archiveCost: 1,
      },
      {
        id: "s5",
        text: "Critics note that green space investment often correlates with gentrification, which displaces long-term residents. Philadelphia's Neighborhood Gardens Trust has pioneered a model that protects community gardens from development pressure.",
        isTrue: true,
        category: "body",
        decayOrder: 4,
        archiveCost: 1,
      },
      {
        id: "s6",
        text: "The EPA estimates that urban tree canopy reduces ambient temperatures by up to 10°F during summer months, which independently correlates with lower rates of heat-related aggression and violence.",
        isTrue: false,
        category: "statistic",
        decayOrder: 2,
        archiveCost: 1,
      },
      {
        id: "s7",
        text: "Several cities, including Detroit and Baltimore, have already begun converting vacant lots into community gardens and pocket parks as part of broader crime reduction strategies.",
        isTrue: true,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
    ],
    factCheckData: {
      sourceCredibility: 65,
      dateAccuracy: true,
      emotionalLanguageScore: 20,
      crossReferenceHits: [
        "Green spaces and crime reduction correlation is supported by multiple studies",
        "The specific 23% figure for low-income neighborhoods is not from this study",
        "EPA tree canopy temperature reduction is typically cited as 2-9°F, not up to 10°F",
        "Philadelphia Neighborhood Gardens Trust is a real organization",
        "Detroit vacant lot conversion programs are well-documented",
      ],
      authorHistory: "Metropolitan Review is a mid-tier publication with generally good reporting",
    },
  },
  // ─── HARD BLOG (Level 7-9) ───
  {
    id: "cache-blog-hard-1",
    title: "I Interviewed 50 Startup Founders Who Failed. Here's the Pattern Nobody Sees.",
    contentType: "blog",
    author: "Priya Sharma",
    date: "January 15, 2026",
    url: "https://founderstories.io/50-failed-startups-pattern",
    difficulty: 8,
    decayDuration: 25,
    sections: [
      {
        id: "s1",
        text: "Over the past two years, I've conducted in-depth interviews with 50 startup founders whose companies failed. The pattern I found challenges the conventional Silicon Valley narrative about failure.",
        isTrue: true,
        category: "headline",
        decayOrder: 5,
        archiveCost: 1,
      },
      {
        id: "s2",
        text: "The number one cause of startup failure wasn't running out of money or bad product-market fit. It was founder burnout — 72% of my interviewees cited mental health deterioration as the primary factor in their decision to shut down.",
        isTrue: false,
        category: "statistic",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s3",
        text: "CB Insights' analysis of startup post-mortems consistently identifies \"no market need\" as the top reason startups fail, appearing in approximately 35% of cases. Running out of cash follows at around 38%.",
        isTrue: true,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s4",
        text: "\"Everyone tells you to 'embrace failure,' but nobody talks about what failure actually does to your relationships, your health, and your sense of identity,\" one founder told me.",
        isTrue: true,
        category: "quote",
        decayOrder: 4,
        archiveCost: 1,
      },
      {
        id: "s5",
        text: "A 2024 study by UC Berkeley found that startup founders are 30% more likely to experience depression than the general population, and twice as likely to have suicidal thoughts.",
        isTrue: false,
        category: "statistic",
        decayOrder: 2,
        archiveCost: 1,
      },
      {
        id: "s6",
        text: "What struck me most was the resilience. Of my 50 interviewees, 34 went on to start new ventures. The ones who succeeded the second time around all had one thing in common: they prioritized their mental health infrastructure first.",
        isTrue: true,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
    ],
    factCheckData: {
      sourceCredibility: 45,
      dateAccuracy: true,
      emotionalLanguageScore: 60,
      crossReferenceHits: [
        "CB Insights data on startup failure reasons is real and widely cited",
        "The 72% burnout claim contradicts established research — burnout is a factor but not the primary cause in most studies",
        "The UC Berkeley '30% more likely' statistic is fabricated — real studies show elevated risk but with different numbers",
        "Founder mental health is a legitimate and growing research area",
      ],
      authorHistory: "Independent blogger, mixes personal interviews with unverified statistics",
    },
  },
  // ─── EASY SOCIAL (Level 1-3) ───
  {
    id: "cache-social-easy-1",
    title: "Just learned something wild about octopuses 🐙",
    contentType: "social",
    author: "NatureFacts_Daily",
    date: "February 11, 2026",
    url: "https://threads.social/@naturefacts_daily/octopus-facts",
    difficulty: 2,
    decayDuration: 55,
    sections: [
      {
        id: "s1",
        text: "Just learned that octopuses have THREE hearts and BLUE blood. Nature is absolutely wild. 🐙💙",
        isTrue: true,
        category: "headline",
        decayOrder: 5,
        archiveCost: 1,
      },
      {
        id: "s2",
        text: "Their blood is blue because it contains copper-based hemocyanin instead of iron-based hemoglobin. This makes them more efficient at transporting oxygen in cold, low-oxygen deep sea environments.",
        isTrue: true,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s3",
        text: "Even crazier: octopuses can edit their own RNA on the fly, meaning they can adapt their brain chemistry in real-time to respond to environmental changes. No other animal on Earth can do this.",
        isTrue: false,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s4",
        text: "Two of their hearts pump blood to the gills, while the third pumps it to the rest of the body. When an octopus swims, the third heart actually stops beating — which is why they prefer crawling.",
        isTrue: true,
        category: "body",
        decayOrder: 4,
        archiveCost: 1,
      },
    ],
    factCheckData: {
      sourceCredibility: 40,
      dateAccuracy: true,
      emotionalLanguageScore: 50,
      crossReferenceHits: [
        "Three hearts and blue blood are well-established octopus facts",
        "RNA editing in cephalopods is real but the claim 'no other animal can do this' is false — other organisms edit RNA too",
        "Heart stopping during swimming is accurate",
      ],
      authorHistory: "Science popularization account — sometimes oversimplifies or exaggerates claims",
    },
  },
  // ─── MEDIUM NEWS (Level 4-6) ───
  {
    id: "cache-news-med-1",
    title: "Remote Work Debate Intensifies as Major Companies Reverse Course",
    contentType: "news",
    author: "Jennifer Liu",
    date: "February 3, 2026",
    url: "https://businesstimes.net/workplace/remote-work-reversal-2026",
    difficulty: 5,
    decayDuration: 40,
    sections: [
      {
        id: "s1",
        text: "The corporate world's relationship with remote work continues to evolve as several Fortune 500 companies mandate full return-to-office policies in early 2026.",
        isTrue: true,
        category: "headline",
        decayOrder: 5,
        archiveCost: 1,
      },
      {
        id: "s2",
        text: "Amazon, JPMorgan Chase, and Goldman Sachs have all required employees to return five days a week, citing collaboration, mentorship, and corporate culture as driving factors.",
        isTrue: true,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s3",
        text: "A Stanford University study led by economist Nicholas Bloom found that fully remote workers are 18% less productive than their in-office counterparts, primarily due to communication barriers and reduced mentorship.",
        isTrue: false,
        category: "statistic",
        decayOrder: 2,
        archiveCost: 1,
      },
      {
        id: "s4",
        text: "Meanwhile, companies like Spotify, Airbnb, and Atlassian continue to embrace flexible or fully remote models, arguing that geographic flexibility allows them to access deeper talent pools.",
        isTrue: true,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s5",
        text: "\"The data does not support a universal answer,\" said Bloom in a recent interview. \"Hybrid arrangements of two to three days in the office seem to have no measurable negative impact on productivity.\"",
        isTrue: true,
        category: "quote",
        decayOrder: 4,
        archiveCost: 1,
      },
      {
        id: "s6",
        text: "According to Gallup, approximately 53% of workers with remote-capable jobs now work in a hybrid arrangement, while only 27% are fully remote and 20% are fully on-site.",
        isTrue: false,
        category: "statistic",
        decayOrder: 2,
        archiveCost: 1,
      },
    ],
    factCheckData: {
      sourceCredibility: 60,
      dateAccuracy: true,
      emotionalLanguageScore: 25,
      crossReferenceHits: [
        "RTO mandates from Amazon, JPMorgan, Goldman are well-documented",
        "Bloom's actual research found fully remote workers about 10% less productive, not 18%",
        "Bloom does advocate for hybrid work — quote is directionally accurate",
        "Gallup numbers are slightly off — real 2025 numbers differ",
        "Spotify, Airbnb remote policies are accurate",
      ],
      authorHistory: "Business Times is a reputable outlet but this article tweaks some statistics",
    },
  },
  // ─── HARD WIKI (Level 7-9) ───
  {
    id: "cache-wiki-hard-1",
    title: "The Great Oxygenation Event",
    contentType: "wiki",
    author: "Encyclopedia Contributors",
    date: "Last edited: January 30, 2026",
    url: "https://freeencyclopedia.org/wiki/Great_Oxygenation_Event",
    difficulty: 8,
    decayDuration: 25,
    sections: [
      {
        id: "s1",
        text: "The Great Oxygenation Event (GOE), also known as the Great Oxidation Event, occurred approximately 2.4 billion years ago during the Paleoproterozoic era. It represents one of the most significant turning points in Earth's history.",
        isTrue: true,
        category: "headline",
        decayOrder: 5,
        archiveCost: 1,
      },
      {
        id: "s2",
        text: "Cyanobacteria, among the earliest photosynthetic organisms, began producing oxygen as a byproduct of photosynthesis. Over millions of years, this oxygen accumulated in the atmosphere after saturating geological oxygen sinks such as dissolved iron in the oceans.",
        isTrue: true,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s3",
        text: "Before the GOE, Earth's atmosphere contained virtually no free oxygen (less than 0.001% compared to today's 21%). The rapid rise in oxygen levels occurred over a span of approximately 20,000 years — geologically instantaneous.",
        isTrue: false,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s4",
        text: "The resulting mass extinction, sometimes called the Oxygen Catastrophe, wiped out a large proportion of anaerobic organisms for which oxygen was toxic. This is considered the first major extinction event in Earth's history.",
        isTrue: true,
        category: "body",
        decayOrder: 4,
        archiveCost: 1,
      },
      {
        id: "s5",
        text: "Evidence for the GOE comes primarily from banded iron formations (BIFs) in geological strata. These formations ceased appearing after the GOE because iron in the oceans was no longer being oxidized and deposited as sediment.",
        isTrue: false,
        category: "body",
        decayOrder: 2,
        archiveCost: 1,
      },
      {
        id: "s6",
        text: "The GOE also triggered the Huronian glaciation (approximately 2.4-2.1 billion years ago), possibly the longest snowball Earth event in history, as the newly abundant oxygen reacted with atmospheric methane — a potent greenhouse gas — reducing its warming effect.",
        isTrue: true,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
    ],
    factCheckData: {
      sourceCredibility: 75,
      dateAccuracy: true,
      emotionalLanguageScore: 10,
      crossReferenceHits: [
        "GOE timing of ~2.4 billion years ago is the scientific consensus",
        "The oxygenation was NOT instantaneous — it occurred over hundreds of millions of years, not 20,000",
        "BIFs actually ceased BECAUSE iron was being oxidized by the new oxygen, not because it wasn't — the reasoning is inverted",
        "Huronian glaciation link to GOE is well-established",
        "Oxygen Catastrophe is a recognized concept in paleobiology",
      ],
      authorHistory: "Community-edited encyclopedia — generally reliable but this article contains subtle inaccuracies",
    },
  },
  // ─── EASY WIKI (Level 1-3) ───
  {
    id: "cache-wiki-easy-1",
    title: "Coffee",
    contentType: "wiki",
    author: "Encyclopedia Contributors",
    date: "Last edited: February 9, 2026",
    url: "https://freeencyclopedia.org/wiki/Coffee",
    difficulty: 1,
    decayDuration: 60,
    sections: [
      {
        id: "s1",
        text: "Coffee is a brewed drink prepared from roasted coffee beans, the seeds of berries from certain flowering plants in the genus Coffea. It is one of the most popular beverages worldwide.",
        isTrue: true,
        category: "headline",
        decayOrder: 5,
        archiveCost: 1,
      },
      {
        id: "s2",
        text: "The two most commercially important coffee species are Coffea arabica (Arabica) and Coffea canephora (Robusta). Arabica accounts for roughly 60-70% of global production.",
        isTrue: true,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s3",
        text: "Coffee was first discovered in Brazil in the 15th century, where local farmers noticed that their goats became unusually energetic after eating berries from a certain tree.",
        isTrue: false,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s4",
        text: "Global coffee consumption exceeds 2 billion cups per day, making it the second most traded commodity after crude oil. Finland has the highest per-capita coffee consumption in the world.",
        isTrue: true,
        category: "statistic",
        decayOrder: 2,
        archiveCost: 1,
      },
    ],
    factCheckData: {
      sourceCredibility: 80,
      dateAccuracy: true,
      emotionalLanguageScore: 5,
      crossReferenceHits: [
        "Coffee origin is Ethiopia, not Brazil — the legend involves an Ethiopian goat herder named Kaldi",
        "Arabica percentage and global consumption figures are approximately correct",
        "Finland does have the highest per-capita coffee consumption",
      ],
      authorHistory: "Community-edited encyclopedia — high reliability on common topics",
    },
  },
  // ─── MEDIUM BLOG (Level 4-6) ───
  {
    id: "cache-blog-med-1",
    title: "The Hidden Cost of Fast Fashion That Your Favorite Brands Don't Want You to Know",
    contentType: "blog",
    author: "Amara Osei",
    date: "February 1, 2026",
    url: "https://sustainableliving.co/fast-fashion-hidden-costs",
    difficulty: 5,
    decayDuration: 40,
    sections: [
      {
        id: "s1",
        text: "Every year, the fashion industry produces over 100 billion garments for a global population of 8 billion people. The math alone should make us pause.",
        isTrue: true,
        category: "headline",
        decayOrder: 5,
        archiveCost: 1,
      },
      {
        id: "s2",
        text: "The fashion industry is responsible for approximately 10% of global carbon emissions — more than all international flights and maritime shipping combined.",
        isTrue: true,
        category: "statistic",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s3",
        text: "A single cotton t-shirt requires roughly 2,700 liters of water to produce — enough drinking water for one person for 2.5 years.",
        isTrue: true,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s4",
        text: "Recent investigations revealed that over 85% of garment workers in Bangladesh, Vietnam, and Cambodia earn less than $1 per day, well below the extreme poverty line set by the World Bank.",
        isTrue: false,
        category: "body",
        decayOrder: 2,
        archiveCost: 1,
      },
      {
        id: "s5",
        text: "Synthetic fabrics like polyester shed microplastics during washing. Research estimates that a single wash cycle can release up to 700,000 microplastic fibers into waterways.",
        isTrue: true,
        category: "body",
        decayOrder: 4,
        archiveCost: 1,
      },
      {
        id: "s6",
        text: "The average American throws away approximately 81.5 pounds of clothing per year, with only 15% of discarded textiles being recycled or donated.",
        isTrue: false,
        category: "statistic",
        decayOrder: 2,
        archiveCost: 1,
      },
    ],
    factCheckData: {
      sourceCredibility: 55,
      dateAccuracy: true,
      emotionalLanguageScore: 55,
      crossReferenceHits: [
        "100 billion garments figure is widely cited and approximately accurate",
        "10% carbon emissions figure is a commonly used estimate",
        "2,700 liters for a cotton t-shirt is a well-established statistic",
        "Garment worker wages are low but the $1/day figure is exaggerated — minimum wages in Bangladesh are approximately $2-3/day",
        "81.5 pounds of clothing thrown away is inflated — the commonly cited figure is around 70-80 pounds, and recycling rates vary",
      ],
      authorHistory: "Sustainability advocacy blog — passionate but sometimes inflates statistics for impact",
    },
  },
  // ─── HARD SOCIAL (Level 7-9) ───
  {
    id: "cache-social-hard-1",
    title: "Unpopular opinion: The 'reading crisis' is completely manufactured",
    contentType: "social",
    author: "BookishProf",
    date: "February 7, 2026",
    url: "https://threads.social/@bookishprof/reading-crisis-thread",
    difficulty: 8,
    decayDuration: 20,
    sections: [
      {
        id: "s1",
        text: "Hot take: the \"reading crisis\" narrative is mostly manufactured panic. People are reading MORE than ever — just differently. A thread on why the data doesn't say what you think it says.",
        isTrue: true,
        category: "headline",
        decayOrder: 5,
        archiveCost: 1,
      },
      {
        id: "s2",
        text: "Total text consumption per person has increased dramatically since 2000. Between emails, messages, articles, and social media, the average adult reads approximately 100,000 words per day — roughly equivalent to a novel.",
        isTrue: false,
        category: "statistic",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s3",
        text: "What IS declining is sustained long-form reading. The NEA's Survey of Public Participation in the Arts shows that the percentage of adults reading literature (novels, short stories, poems) has dropped from 57% in 1982 to about 53% in 2022.",
        isTrue: true,
        category: "body",
        decayOrder: 3,
        archiveCost: 1,
      },
      {
        id: "s4",
        text: "Meanwhile, audiobook consumption grew by 25% in 2024 alone, and BookTok has driven physical book sales to their highest levels since 2004. Young people aren't abandoning books — they're discovering them through new channels.",
        isTrue: false,
        category: "body",
        decayOrder: 4,
        archiveCost: 1,
      },
      {
        id: "s5",
        text: "The real concern shouldn't be about quantity of reading — it should be about quality of attention. Deep reading builds different cognitive pathways than scrolling. Both have value, but they're not interchangeable.",
        isTrue: true,
        category: "body",
        decayOrder: 2,
        archiveCost: 1,
      },
    ],
    factCheckData: {
      sourceCredibility: 50,
      dateAccuracy: true,
      emotionalLanguageScore: 40,
      crossReferenceHits: [
        "Total text consumption has increased but 100,000 words/day is significantly inflated — estimates vary from 20,000-50,000",
        "NEA reading survey data is real but the 53% figure is approximately right for recent years",
        "Audiobook growth was about 12% in 2024, not 25% — and BookTok impact on sales is real but 'highest since 2004' is inaccurate",
        "Deep reading vs. skimming distinction is supported by cognitive science research",
      ],
      authorHistory: "Academic account — makes good arguments but cherry-picks and inflates supporting statistics",
    },
  },
];

/**
 * Get cached page content filtered by difficulty and content type.
 */
export function getCachedPage(
  difficulty: number,
  contentType?: PageContent["contentType"]
): PageContent | null {
  const candidates = CACHED_PAGES.filter((p) => {
    const diffMatch = Math.abs(p.difficulty - difficulty) <= 2;
    const typeMatch = !contentType || p.contentType === contentType;
    return diffMatch && typeMatch;
  });

  if (candidates.length === 0) return CACHED_PAGES[0] ?? null;
  return candidates[Math.floor(Math.random() * candidates.length)] ?? null;
}

/**
 * Get a random cached page that hasn't been used recently.
 */
export function getRandomCachedPage(
  usedIds: string[] = [],
  difficulty?: number
): PageContent {
  let candidates = CACHED_PAGES.filter((p) => !usedIds.includes(p.id));
  if (difficulty !== undefined) {
    const diffFiltered = candidates.filter(
      (p) => Math.abs(p.difficulty - difficulty) <= 2
    );
    if (diffFiltered.length > 0) candidates = diffFiltered;
  }
  if (candidates.length === 0) candidates = CACHED_PAGES;
  return candidates[Math.floor(Math.random() * candidates.length)]!;
}
